apiVersion: v1
data:
  DATABASE_NAME: todo
  DATABASE_PASSWORD: redhat123
  DATABASE_SVC_HOSTNAME: tododb
  DATABASE_USER: todoapp
kind: ConfigMap
metadata:
  creationTimestamp: "2024-03-04T00:12:56Z"
  name: app-config
  namespace: developer-todo-migrate
  resourceVersion: "3586386"
  uid: 1375042d-e9d2-4df0-9f41-27692c0769e1
